### ISSUE TITLE
Send any command(s)

### ISSUE THREAD

**Issue by jdebardi** [jdebardi/homebridge-sky-q#2]
Allow user to send any commands to the sky box

Add the optional "cmd" config to the accessory with comma separate list of commands to send.
See https://github.com/dalhundal/sky-remote for list of supported commands.

Omitting this will default to the previous 'power' command.

When running without cmd or if cmd='power' switch state works, in other cases switch state is disabled to avoid confusion of box status (produces a (!) error on the accessory in Home app but can't find another way to prevent switch toggling right now).

Working on the branch https://github.com/jdebardi/homebridge-sky-q/tree/Any-Cmd
If you wish to test please take code from there and NOT the master branch!

Example config
        {
            "accessory": "SkyQPlay",
            "ipAddress": "10.11.12.174",
            "name": "Sky Q Box Play",
            "cmd": "1,2,3"
        }

**Comment by obarber** [comment]
Annoyingly, I just installed this plugin, and although it worked, I uninstalled it, but now my homebridge won't run...

**Comment by obarber** [comment]
I installed it, and it works to an extent.

I have set up a couple of buttons, they will work once, but after that, every press will show this in terminal: 

"[2018-2-12 19:51:32] [Sky Q Mini] Sending "" command to Sky Q Mini..."

**Comment by jdebardi** [comment]
I did submit a fix 32 mins ago for a crash, if you downloaded it before that try again.
It looks like it’s sending an empty command tho. Can you post the config.json you used?

**Comment by jdebardi** [comment]
Ok. Reproduced. Will look into it

**Comment by obarber** [comment]
Do you have reddit at all, just be easier to message you on there if you do. Because I'd like to message you about something off topic.

**Comment by jdebardi** [comment]
Yep https://www.reddit.com/u/josedebardi/?st=JDKP3JTM&sh=c21af2fc

**Comment by jdebardi** [comment]
WOW - that was hard work! Still don't understand why it didn't like how I'd passed the cmd variable around, but re-arranged the code to make it work in the end! Works for as many button presses as you want now!

**Comment by jdebardi** [comment]
OK I think I've done all that is reasonable. See #1 and the Readme of the Any-Cmd branch for info.
Appreciate it if you could have a play with it and feed back!

**Comment by neiloakley** [comment]
Just installed `npm install -g homebridge-sky-q` and then copied your index.js into the one in my roaming node folder. 

But now i get this error:

`The Requested accessory 'SkyQ' was not registered by any plugin`

This is my config.json

{
	"bridge": {
		"name": "Homebridge",
		"username": "XX:XX:XX:XX:XX:XX",
		"port": 51826,
		"pin": "031-45-156"
	},

	"description": "JSON API",



  "accessories": [
{
    "accessory": "SkyQ",
    "name": "Sky Q",
    "ipAddress": "192.168.0.2"
},
{
    "accessory": "SkyQ",
    "name": "Sky Q Mini Bedroom",
    "ipAddress": "192.168.0.26"
}

],

**Comment by jdebardi** [comment]
@neiloakley sorry - my bad - the version I uploaded still had my 'dev' name to avoid conflict with the mainline one (as I have both installed on my homebridge). I've fixed it now if you re-download it.

**Comment by neiloakley** [comment]
Great - sorted now. On/Off works fine, state awareness seems good as well. Now Siri can tell me if it's on or off!

I just need to figure out how to use some of the other commands, so that i can effectively tell Siri to go to a particular channel.

**Comment by jdebardi** [comment]
Just uploaded another version which makes it more Siri friendly (he doesn't like commands that take too long so I tell him it's done before it really is - if using the Home app the switch will remain 'on' until it's really complete though so you can still visually see if its on-going when not using Siri).

Here's a couple of my 'go to channel' and 'play a recorded programme from the planner' (can you tell I have a 2 yr old!)
I can say 'Hey Siri put Peppa Pig on' and it works perfectly, even if the Sky/TV box is off to start with (thats to the autoOn option)!

        {
            "accessory": "SkyQ",
            "ipAddress": "10.11.12.174",
	    "name": "Nick Junior",
	    "cmd": "backup,backup,backup,6,3,7",
	    "autoOn": true,
        },
        {
            "accessory": "SkyQ",
            "ipAddress": "10.11.12.174",
	    "name": "Peppa Pig",
	    "cmd": "search,search,7,3,3,7,right,right,right,select,down,down,down,down,down,down,down,up,select,up,up,up,up,up,right,right,select",
	    "autoOn": true,
        }

See the readme for the new 'Tips' section I've added!

**Comment by jdebardi** [comment]
Merged to master
